version: "3.8"

services:
  node:
    image: node:16
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=main
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  server:
    build:
      dockerfile: Dockerfile
      context: ./backend
    command: npm run start:dev
    volumes:
      - ./backend:/app
    ports:
      - "5000:3000"
