version: "3.8"

services:
  node:
    image: node:16
    volumes:
      - shared-node_modules:/backend/node_modules
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=main
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  backend:
    build:
      dockerfile: Dockerfile
      context: ./backend
    command: npm run start:dev
    volumes:
      - /backend/node_modules # Exclude node_modules from host.
      - shared-node_modules:/backend/node_modules
      - ./backend:/backend
    ports:
      - "5000:3000"
    depends_on:
      - db

volumes:
  shared-node_modules:
