name: Test

on: [push]

jobs:
  test:
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: main
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - "5432:5432"

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"
          cache: "npm"
      - run: npm ci
        working-directory: "./backend"
      - run: npm run test
        working-directory: "./backend"
